import { Product, Vendor, Order } from '../types/ecommerce';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    titleEn: 'Golden Khmer Pure Silk Scarf',
    titleKm: 'ក្រមា និងកន្សែងសូត្រមាសខ្មែរប្រណីត',
    descEn: 'Authentic 100% handwoven Cambodian Golden Silk scarf crafted with traditional heritage patterns from Takeo province.',
    descKm: 'កន្សែងសូត្រមាសខ្មែរត្បាញដោយដៃសុទ្ធ ១០០% តាមក្បាច់បុរាណប្រពៃណីពីខេត្តតាកែវ។',
    price: 48.0,
    originalPrice: 65.0,
    rating: 4.9,
    reviewsCount: 142,
    category: 'artisan',
    vendorId: 'vendor-1',
    vendorName: 'Angkor Heritage Crafts',
    stock: 18,
    iconName: 'sparkles',
    accentBg: '#FEF3C7',
    badge: 'Best Seller',
    isFeatured: true,
  },
  {
    id: 'prod-2',
    titleEn: 'Mondulkiri Organic Peaberry Coffee (500g)',
    titleKm: 'កាហ្វេពូជពិសេសមណ្ឌលគិរីសរីរាង្គ (៥០០ក្រាម)',
    descEn: 'Premium high-altitude roasted coffee beans grown in the volcanic soils of Mondulkiri highlands with chocolate & fruit notes.',
    descKm: 'គ្រាប់កាហ្វេដាំលើដីភ្នំភ្លើងខ្ពង់រាបមណ្ឌលគិរី ក្លិនឈ្ងុយប្លែក មានរសជាតិសូកូឡា និងផ្លែឈើ។',
    price: 14.5,
    originalPrice: 18.0,
    rating: 4.8,
    reviewsCount: 96,
    category: 'food',
    vendorId: 'vendor-2',
    vendorName: 'Mondulkiri Highland Co.',
    stock: 45,
    iconName: 'cafe',
    accentBg: '#FED7AA',
    badge: 'Organic',
    isFeatured: true,
  },
  {
    id: 'prod-3',
    titleEn: 'Pro Wireless ANC Earbuds (Spatial Audio)',
    titleKm: 'កាសឥតខ្សែ Pro កាត់បន្ថយសំឡេងរំខាន',
    descEn: 'Studio-grade acoustic sound, active noise cancellation, 36-hour battery life, and Bluetooth 5.4 wireless streaming.',
    descKm: 'សំឡេងកម្រិតស្ទូឌីយោ បច្ចេកវិទ្យាកាត់បន្ថយសំឡេងរំខាន ថ្មកាន់បាន ៣៦ ម៉ោង និងប៊្លូធូស ៥.៤។',
    price: 89.0,
    originalPrice: 120.0,
    rating: 4.7,
    reviewsCount: 310,
    category: 'electronics',
    vendorId: 'vendor-3',
    vendorName: 'NeoTech Innovations',
    stock: 24,
    iconName: 'headset',
    accentBg: '#E0E7FF',
    badge: '⚡ Deal -26%',
    isFeatured: true,
  },
  {
    id: 'prod-4',
    titleEn: 'Contemporary Khmer Kroma Bomber Jacket',
    titleKm: 'អាវរងាបែបទំនើបក្បាច់ក្រមាខ្មែរ',
    descEn: 'Modern streetwear fusion blending water-resistant windbreaker fabric with genuine woven Khmer Kroma accents.',
    descKm: 'អាវម៉ូដទាន់សម័យដែលរួមបញ្ចូលសាច់ក្រណាត់ការពារទឹកភ្លៀង ជាមួយក្បាច់ក្រមាខ្មែរពិតប្រាកដ។',
    price: 52.0,
    originalPrice: 70.0,
    rating: 4.9,
    reviewsCount: 78,
    category: 'fashion',
    vendorId: 'vendor-1',
    vendorName: 'Angkor Heritage Crafts',
    stock: 12,
    iconName: 'shirt',
    accentBg: '#FCE7F3',
    badge: 'Trending',
    isFeatured: false,
  },
  {
    id: 'prod-5',
    titleEn: 'Handmade Rattan & Bamboo Ambient Lamp',
    titleKm: 'ចង្កៀងតុបតែងផ្ទះផ្តៅ និងឫស្សីធ្វើដោយដៃ',
    descEn: 'Natural sustainable rattan bedside lamp casting warm ambient geometric shadows, handcrafted in Siem Reap.',
    descKm: 'ចង្កៀងផ្តៅធម្មជាតិសម្រាប់បន្ទប់គេង បញ្ចេញពន្លឺស្រទន់ស្រស់ស្អាត ផលិតនៅខេត្តសៀមរាប។',
    price: 36.0,
    originalPrice: 45.0,
    rating: 4.6,
    reviewsCount: 52,
    category: 'home',
    vendorId: 'vendor-1',
    vendorName: 'Angkor Heritage Crafts',
    stock: 8,
    iconName: 'bulb',
    accentBg: '#D1FAE5',
    isFeatured: false,
  },
  {
    id: 'prod-6',
    titleEn: 'Kampot PGI Black & Red Peppercorns Set',
    titleKm: 'ម្រេចខ្មៅ និងម្រេចក្រហមកំពត PGI លំដាប់ពិភពលោក',
    descEn: 'Internationally protected geographical indicator Kampot pepper with intense aroma and exquisite peppery warmth.',
    descKm: 'ម្រេចកំពតមានស្លាកសម្គាល់ភូមិសាស្ត្រទំនិញ PGI លំដាប់ពិភពលោក ក្លិនឈ្ងុយកម្រិតខ្ពស់។',
    price: 19.9,
    originalPrice: 25.0,
    rating: 5.0,
    reviewsCount: 220,
    category: 'food',
    vendorId: 'vendor-2',
    vendorName: 'Mondulkiri Highland Co.',
    stock: 60,
    iconName: 'restaurant',
    accentBg: '#FEE2E2',
    badge: 'PGI Certified',
    isFeatured: true,
  },
  {
    id: 'prod-7',
    titleEn: 'Ultra-Slim Magnesium Power Bank 20000mAh',
    titleKm: 'ដុំសាកថ្មចល័ត Ultra-Slim 20000mAh សាកលឿន 65W',
    descEn: '65W Fast Charging USB-C Power Delivery laptop and phone power bank with smart LCD status display.',
    descKm: 'ដុំសាកថ្មស្តើងកម្លាំងខ្លាំង 65W PD អាចសាកកុំព្យូទ័រយួរដៃ និងទូរស័ព្ទ អមដោយអេក្រង់ LCD។',
    price: 42.0,
    originalPrice: 55.0,
    rating: 4.7,
    reviewsCount: 88,
    category: 'electronics',
    vendorId: 'vendor-3',
    vendorName: 'NeoTech Innovations',
    stock: 30,
    iconName: 'battery-charging',
    accentBg: '#CFFAFE',
    isFeatured: false,
  },
  {
    id: 'prod-8',
    titleEn: 'Artisanal Handwoven Water Hyacinth Bag',
    titleKm: 'កាបូបយួរកំប្លោកធម្មជាតិត្បាញដោយដៃ',
    descEn: 'Eco-friendly lightweight handbag handwoven from Tonle Sap water hyacinth with leatherette handle straps.',
    descKm: 'កាបូបយួរដៃអេកូឡូស៊ីត្បាញពីកំប្លោកធម្មជាតិតំបន់បឹងទន្លេសាប មានខ្សែស្បែកយ៉ាងរឹងមាំ។',
    price: 28.0,
    originalPrice: 38.0,
    rating: 4.8,
    reviewsCount: 64,
    category: 'artisan',
    vendorId: 'vendor-1',
    vendorName: 'Angkor Heritage Crafts',
    stock: 15,
    iconName: 'bag-handle',
    accentBg: '#F3E8FF',
    badge: 'Eco Friendly',
    isFeatured: false,
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Angkor Heritage Crafts',
    nameKm: 'សិប្បកម្មបេតិកភណ្ឌអង្គរ',
    ownerName: 'Sokha Meng',
    rating: 4.9,
    salesCount: 840,
    revenue: 38400.0,
    productsCount: 4,
    status: 'active',
    commissionRate: 8.0,
    joinedDate: 'Jan 2025',
  },
  {
    id: 'vendor-2',
    name: 'Mondulkiri Highland Co.',
    nameKm: 'កាហ្វេ និងកសិផលខ្ពង់រាបមណ្ឌលគិរី',
    ownerName: 'Channary Voeun',
    rating: 4.9,
    salesCount: 1250,
    revenue: 26800.0,
    productsCount: 2,
    status: 'active',
    commissionRate: 8.0,
    joinedDate: 'Feb 2025',
  },
  {
    id: 'vendor-3',
    name: 'NeoTech Innovations',
    nameKm: 'ហាងបច្ចេកវិទ្យា NeoTech',
    ownerName: 'Vatanak Chen',
    rating: 4.7,
    salesCount: 620,
    revenue: 41200.0,
    productsCount: 2,
    status: 'active',
    commissionRate: 8.0,
    joinedDate: 'Mar 2025',
  },
  {
    id: 'vendor-4',
    name: 'Battambang Organic Produce',
    nameKm: 'កសិផលសរីរាង្គបាត់ដំបង',
    ownerName: 'Dara Pich',
    rating: 4.5,
    salesCount: 110,
    revenue: 3400.0,
    productsCount: 0,
    status: 'pending',
    commissionRate: 8.0,
    joinedDate: 'Oct 2026',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ORD-8821',
    customerName: 'Bunsan Doe',
    customerPhone: '+855 12 889 900',
    address: 'St 2004, Sen Sok, Phnom Penh',
    items: [
      { product: INITIAL_PRODUCTS[0], quantity: 1 },
      { product: INITIAL_PRODUCTS[1], quantity: 2 },
    ],
    total: 77.0,
    status: 'processing',
    date: 'Today, 2:15 PM',
    paymentMethod: 'ABA PAY / KHQR',
    vendorId: 'vendor-1',
  },
  {
    id: 'ORD-8742',
    customerName: 'Chenda K.',
    customerPhone: '+855 98 443 211',
    address: 'Toul Tompoung 1, Chamkarmon, Phnom Penh',
    items: [{ product: INITIAL_PRODUCTS[2], quantity: 1 }],
    total: 89.0,
    status: 'shipped',
    date: 'Yesterday, 10:30 AM',
    paymentMethod: 'ABA PAY / KHQR',
    vendorId: 'vendor-3',
  },
  {
    id: 'ORD-8610',
    customerName: 'Vibol Sovann',
    customerPhone: '+855 77 123 456',
    address: 'Street 08, Svay Dangkum, Siem Reap',
    items: [
      { product: INITIAL_PRODUCTS[5], quantity: 2 },
      { product: INITIAL_PRODUCTS[1], quantity: 1 },
    ],
    total: 54.3,
    status: 'delivered',
    date: 'Sep 29, 2026',
    paymentMethod: 'Cash on Delivery',
    vendorId: 'vendor-2',
  },
];
